import os
from datetime import date
import pandas as pd
from g import subjects,db_marks,pass_update,st_db,db_update,logins_db,stud_db_attd,st_sub_db_attd,st_db_date_atted
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import PySide2
from Custom_Widgets.Widgets import QCustomSlideMenu
from Custom_Widgets.Widgets import QCustomStackedWidget
import i_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(2033, 991)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(400, 50))
        MainWindow.setStyleSheet(u"*{\n"
"border:none;\n"
"background-color:transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff;\n"
"}\n"
"#centralwidget{\n"
"	border-image: url(:/newPrefix/3.JPG);\n"
"}\n"
"#a,#b,#a_2,#b_2,#widget_7,#widget_9,#widget_10,#widget_11,#widget_13,#widget_18,#widget_19,#widget_24,#widget_25{\n"
"background-color: rgba(0,0,0,150);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(255,255,255);\n"
"}\n"
"#label_2{\n"
"color:rgb(0,0,0)\n"
"}\n"
"QPushButton{\n"
"text-align:left;\n"
"padding:5px 10px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius:10px;\n"
"background-color: #1b1b27;\n"
"}\n"
"#home_btn{\n"
"border-left: 3px solid rgb(255, 0, 0);\n"
"font-weight: bold\n"
"}\n"
"QLineEdit,QComboBox{\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"color: rgb(255,255,255);\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"backgrounnd-color: rgb(34,36,44);\n"
"}\n"
"QComboBox:hover{\n"
"border:2px solid rgb(97, 97, 97);}\n"
"QLineEdit:hover{\n"
"bord"
                        "er:2px solid rgb(97, 97, 97);}\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(97, 97, 97);\n"
"background-color:rgb(43,45,56);\n"
"}\n"
"\n"
"#logout,#la,#ra,#Update_ph,#Update_pass{\n"
"text-align:center;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:25px;\n"
"color: rgb(0,0,0);\n"
"}\n"
"#Update_ph:hover{\n"
"text-align:center;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:25px;\n"
"color: rgb(255,255,255);\n"
"}\n"
"#Update_pass:hover{\n"
"text-align:center;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:25px;\n"
"color: rgb(255,255,255);\n"
"}\n"
"#logout:hover{\n"
"text-align:center;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:25px;\n"
"color: rgb(255,255,255);\n"
"}\n"
"#la:hover{\n"
"text-align:center;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:25px;\n"
"color: rgb(255,255,255);\n"
"}\n"
"#ra:hover{\n"
"text-align:center;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:25px;\n"
"color: rgb(255,255,255);\n"
"}\n"
"#T_name,#T_Ph,#T_ID,"
                        "#Cls_ID,#Th,#Ah,#Ph,#P,#Sub1,#Sub2,#Sub3,#Sub4,#Sub5,#Sub1_2,#Sub2_5,#Sub3_2,#Sub4_2,#Sub5_2,#Tp_,#Sub1m,#Sub2m,#Sub3m,#Sub4m,#Sub5m{\n"
"border:3px solid rgb(255,255, 255);\n"
"border-radius:25px;\n"
"background-color: rgba(0,0,0,150);}\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Title = QWidget(self.centralwidget)
        self.Title.setObjectName(u"Title")
        self.horizontalLayout_3 = QHBoxLayout(self.Title)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.frame_6 = QFrame(self.Title)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_3.addWidget(self.frame_6, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.label_2 = QLabel(self.Title)
        self.label_2.setObjectName(u"label_2")
        font = QFont()
        font.setFamily(u"BlackChancery")
        font.setPointSize(45)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.horizontalLayout_3.addWidget(self.label_2)
        self.logout = QPushButton(self.Title)
        self.logout.setObjectName(u"logout")
        self.logout.setMinimumSize(QSize(100, 50))
        font1 = QFont()
        font1.setFamily(u"white allies")
        font1.setPointSize(19)
        self.logout.setFont(font1)
        icon = QIcon()
        icon.addFile(u"l.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logout.setIcon(icon)
        self.logout.setIconSize(QSize(36, 36))
        self.horizontalLayout_3.addWidget(self.logout, 0, Qt.AlignRight)
        self.verticalLayout.addWidget(self.Title)
        self.Body = QWidget(self.centralwidget)
        self.Body.setObjectName(u"Body")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy2)
        self.horizontalLayout = QHBoxLayout(self.Body)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.left_menu = QCustomSlideMenu(self.Body)
        self.left_menu.setObjectName(u"left_menu")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.left_menu.sizePolicy().hasHeightForWidth())
        self.left_menu.setSizePolicy(sizePolicy3)
        self.left_menu.setMinimumSize(QSize(200, 0))
        self.left_menu.setCursor(QCursor(Qt.ArrowCursor))
        self.left_menu.setStyleSheet(u"")
        self.verticalLayout_5 = QVBoxLayout(self.left_menu)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.widget = QWidget(self.left_menu)
        self.widget.setObjectName(u"widget")
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.verticalLayout_6 = QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(10, 5, 0, 0)
        self.frame = QFrame(self.widget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frame)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.home_btn = QPushButton(self.frame)
        self.home_btn.setObjectName(u"home_btn")
        font2 = QFont()
        font2.setFamily(u"Maiandra GD")
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        self.home_btn.setFont(font2)
        self.home_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_7.addWidget(self.home_btn)
        self.Updt_Details = QPushButton(self.frame)
        self.Updt_Details.setObjectName(u"Updt_Details")
        font3 = QFont()
        font3.setFamily(u"Maiandra GD")
        font3.setPointSize(12)
        self.Updt_Details.setFont(font3)
        self.Updt_Details.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_7.addWidget(self.Updt_Details)
        self.Attd_verify_Uptd = QPushButton(self.frame)
        self.Attd_verify_Uptd.setObjectName(u"Attd_verify_Uptd")
        self.Attd_verify_Uptd.setMinimumSize(QSize(0, 29))
        font4 = QFont()
        font4.setFamily(u"Maiandra GD")
        font4.setPointSize(11)
        self.Attd_verify_Uptd.setFont(font4)
        self.verticalLayout_7.addWidget(self.Attd_verify_Uptd)
        self.Academics = QPushButton(self.frame)
        self.Academics.setObjectName(u"Academics")
        self.Academics.setMinimumSize(QSize(0, 29))
        font5 = QFont()
        font5.setPointSize(12)
        self.Academics.setFont(font5)
        self.verticalLayout_7.addWidget(self.Academics)
        self.verticalLayout_6.addWidget(self.frame)
        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(self.verticalSpacer)
        self.frame_2 = QFrame(self.widget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(180, 0))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.Help = QPushButton(self.frame_2)
        self.Help.setObjectName(u"Help")
        self.Help.setEnabled(True)
        self.Help.setFont(font3)
        self.Help.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_2.addWidget(self.Help)
        self.Settings = QPushButton(self.frame_2)
        self.Settings.setObjectName(u"Settings")
        self.Settings.setEnabled(True)
        self.Settings.setFont(font3)
        self.Settings.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_2.addWidget(self.Settings)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.left_menu)
        self.widget_14 = QWidget(self.Body)
        self.widget_14.setObjectName(u"widget_14")
        self.content = QWidget(self.widget_14)
        self.content.setObjectName(u"content")
        self.content.setGeometry(QRect(0, 0, 1940, 889))
        self.verticalLayout_4 = QVBoxLayout(self.content)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.main_pages = QCustomStackedWidget(self.content)
        self.main_pages.setObjectName(u"main_pages")
        font6 = QFont()
        font6.setPointSize(18)
        self.main_pages.setFont(font6)
        self.main_pages.setFrameShadow(QFrame.Sunken)
        self.Home = QWidget()
        self.Home.setObjectName(u"Home")
        self.Home.setStyleSheet(u"")
        self.widget_3 = QWidget(self.Home)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(0, 0, 2031, 1501))
        sizePolicy4 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy4)
        self.widget_3.setMinimumSize(QSize(1000, 1500))
        self.widget_4 = QWidget(self.widget_3)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(0, 0, 1831, 100))
        sizePolicy5 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy5)
        self.widget_4.setMinimumSize(QSize(1000, 100))
        self.horizontalLayout_4 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.horizontalLayout_4.setContentsMargins(3, 3, -1, -1)
        self.T_name = QWidget(self.widget_4)
        self.T_name.setObjectName(u"T_name")
        sizePolicy6 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.T_name.sizePolicy().hasHeightForWidth())
        self.T_name.setSizePolicy(sizePolicy6)
        self.T_name.setMinimumSize(QSize(500, 0))
        self.T_name.setMaximumSize(QSize(300, 100))
        self.Tname = QLabel(self.T_name)
        self.Tname.setObjectName(u"Tname")
        self.Tname.setGeometry(QRect(10, 17, 481, 51))
        font7 = QFont()
        font7.setFamily(u"Maiandra GD")
        font7.setPointSize(20)
        self.Tname.setFont(font7)
        self.horizontalLayout_4.addWidget(self.T_name)
        self.T_ID = QWidget(self.widget_4)
        self.T_ID.setObjectName(u"T_ID")
        sizePolicy6.setHeightForWidth(self.T_ID.sizePolicy().hasHeightForWidth())
        self.T_ID.setSizePolicy(sizePolicy6)
        self.T_ID.setMinimumSize(QSize(200, 0))
        self.T_ID.setMaximumSize(QSize(200, 100))
        self.Tid = QLabel(self.T_ID)
        self.Tid.setObjectName(u"Tid")
        self.Tid.setGeometry(QRect(10, 17, 281, 51))
        self.Tid.setFont(font7)
        self.horizontalLayout_4.addWidget(self.T_ID)
        self.Cls_ID = QWidget(self.widget_4)
        self.Cls_ID.setObjectName(u"Cls_ID")
        sizePolicy6.setHeightForWidth(self.Cls_ID.sizePolicy().hasHeightForWidth())
        self.Cls_ID.setSizePolicy(sizePolicy6)
        self.Cls_ID.setMinimumSize(QSize(225, 0))
        self.Cls_ID.setMaximumSize(QSize(225, 100))
        self.Cid = QLabel(self.Cls_ID)
        self.Cid.setObjectName(u"Cid")
        self.Cid.setGeometry(QRect(10, 17, 351, 51))
        self.Cid.setFont(font7)
        self.horizontalLayout_4.addWidget(self.Cls_ID)
        self.T_Ph = QWidget(self.widget_4)
        self.T_Ph.setObjectName(u"T_Ph")
        sizePolicy6.setHeightForWidth(self.T_Ph.sizePolicy().hasHeightForWidth())
        self.T_Ph.setSizePolicy(sizePolicy6)
        self.T_Ph.setMinimumSize(QSize(375, 0))
        self.T_Ph.setMaximumSize(QSize(300, 100))
        self.TPh = QLabel(self.T_Ph)
        self.TPh.setObjectName(u"TPh")
        self.TPh.setGeometry(QRect(10, 17, 361, 51))
        self.TPh.setFont(font7)
        self.horizontalLayout_4.addWidget(self.T_Ph)
        self.widget_6 = QWidget(self.widget_3)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(0, 100, 1721, 800))
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QSize(0, 500))
        self.widget_6.setMaximumSize(QSize(16777215, 16777215))
        self.widget_6.setStyleSheet(u"")
        self.gridLayout_2 = QGridLayout(self.widget_6)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.a_2 = QWidget(self.widget_6)
        self.a_2.setObjectName(u"a_2")
        self.a_2.setMaximumSize(QSize(500, 16777215))
        self.calendar = QCalendarWidget(self.a_2)
        self.calendar.setObjectName(u"calendar")
        self.calendar.setGeometry(QRect(0, 0, 501, 351))
        font8 = QFont()
        font8.setFamily(u"Maiandra GD")
        self.calendar.setFont(font8)
        self.calendar.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,150);\n"
"selection-background-color: rgb(255,255,255);\n"
"alternate-background-color: rgb(83, 83, 83);\n"
"selection-color: rgb(0,0,0);\n"
"font-size:15px;\n"
"width:100px;\n"
"icon-size:35px,35px;")
        self.calendar.setFirstDayOfWeek(Qt.Sunday)
        self.calendar.setGridVisible(False)
        self.calendar.setHorizontalHeaderFormat(QCalendarWidget.ShortDayNames)
        self.calendar.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)
        self.gridLayout_2.addWidget(self.a_2, 0, 0, 1, 1)
        self.b_2 = QWidget(self.widget_6)
        self.b_2.setObjectName(u"b_2")
        self.b_2.setMaximumSize(QSize(16777215, 350))
        self.Tname_2 = QLabel(self.b_2)
        self.Tname_2.setObjectName(u"Tname_2")
        self.Tname_2.setGeometry(QRect(450, 20, 361, 51))
        font9 = QFont()
        font9.setFamily(u"Maiandra GD")
        font9.setPointSize(31)
        self.Tname_2.setFont(font9)
        self.Th = QWidget(self.b_2)
        self.Th.setObjectName(u"Th")
        self.Th.setGeometry(QRect(220, 160, 140, 88))
        sizePolicy6.setHeightForWidth(self.Th.sizePolicy().hasHeightForWidth())
        self.Th.setSizePolicy(sizePolicy6)
        self.Th.setMinimumSize(QSize(100, 0))
        self.Th.setMaximumSize(QSize(300, 100))
        self.Th_ = QLabel(self.Th)
        self.Th_.setObjectName(u"Th_")
        self.Th_.setGeometry(QRect(0, 20, 131, 51))
        font10 = QFont()
        font10.setFamily(u"Maiandra GD")
        font10.setPointSize(22)
        self.Th_.setFont(font10)
        self.Th_.setAlignment(Qt.AlignCenter)
        self.Tname_5 = QLabel(self.b_2)
        self.Tname_5.setObjectName(u"Tname_5")
        self.Tname_5.setGeometry(QRect(210, 100, 201, 51))
        self.Tname_5.setFont(font10)
        self.Tname_6 = QLabel(self.b_2)
        self.Tname_6.setObjectName(u"Tname_6")
        self.Tname_6.setGeometry(QRect(420, 100, 201, 51))
        self.Tname_6.setFont(font10)
        self.Ph = QWidget(self.b_2)
        self.Ph.setObjectName(u"Ph")
        self.Ph.setGeometry(QRect(440, 160, 140, 88))
        sizePolicy6.setHeightForWidth(self.Ph.sizePolicy().hasHeightForWidth())
        self.Ph.setSizePolicy(sizePolicy6)
        self.Ph.setMinimumSize(QSize(100, 0))
        self.Ph.setMaximumSize(QSize(300, 100))
        self.Ph_ = QLabel(self.Ph)
        self.Ph_.setObjectName(u"Ph_")
        self.Ph_.setGeometry(QRect(0, 20, 141, 51))
        self.Ph_.setFont(font10)
        self.Ph_.setAlignment(Qt.AlignCenter)
        self.Tname_7 = QLabel(self.b_2)
        self.Tname_7.setObjectName(u"Tname_7")
        self.Tname_7.setGeometry(QRect(630, 100, 201, 51))
        self.Tname_7.setFont(font10)
        self.Ah = QWidget(self.b_2)
        self.Ah.setObjectName(u"Ah")
        self.Ah.setGeometry(QRect(650, 160, 140, 88))
        sizePolicy6.setHeightForWidth(self.Ah.sizePolicy().hasHeightForWidth())
        self.Ah.setSizePolicy(sizePolicy6)
        self.Ah.setMinimumSize(QSize(100, 0))
        self.Ah.setMaximumSize(QSize(300, 100))
        self.Ah_ = QLabel(self.Ah)
        self.Ah_.setObjectName(u"Ah_")
        self.Ah_.setGeometry(QRect(0, 20, 141, 51))
        self.Ah_.setFont(font10)
        self.Ah_.setAlignment(Qt.AlignCenter)
        self.Tname_8 = QLabel(self.b_2)
        self.Tname_8.setObjectName(u"Tname_8")
        self.Tname_8.setGeometry(QRect(840, 100, 201, 51))
        self.Tname_8.setFont(font10)
        self.P = QWidget(self.b_2)
        self.P.setObjectName(u"P")
        self.P.setGeometry(QRect(840, 160, 140, 88))
        sizePolicy6.setHeightForWidth(self.P.sizePolicy().hasHeightForWidth())
        self.P.setSizePolicy(sizePolicy6)
        self.P.setMinimumSize(QSize(100, 0))
        self.P.setMaximumSize(QSize(300, 100))
        self.P_ = QLabel(self.P)
        self.P_.setObjectName(u"P_")
        self.P_.setGeometry(QRect(0, 20, 141, 51))
        self.P_.setFont(font10)
        self.P_.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.b_2, 0, 1, 1, 1)
        self.d_2 = QWidget(self.widget_6)
        self.d_2.setObjectName(u"d_2")
        self.widget_7 = QWidget(self.d_2)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(0, 0, 821, 421))
        self.subattd = QLabel(self.widget_7)
        self.subattd.setObjectName(u"subattd")
        self.subattd.setGeometry(QRect(230, 0, 441, 51))
        font11 = QFont()
        font11.setFamily(u"Maiandra GD")
        font11.setPointSize(28)
        self.subattd.setFont(font11)
        self.Subj1_6 = QLabel(self.widget_7)
        self.Subj1_6.setObjectName(u"Subj1_6")
        self.Subj1_6.setGeometry(QRect(40, 60, 371, 51))
        font12 = QFont()
        font12.setFamily(u"Maiandra GD")
        font12.setPointSize(18)
        self.Subj1_6.setFont(font12)
        self.Subj1_6.setAlignment(Qt.AlignCenter)
        self.Sub1 = QWidget(self.widget_7)
        self.Sub1.setObjectName(u"Sub1")
        self.Sub1.setGeometry(QRect(160, 110, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub1.sizePolicy().hasHeightForWidth())
        self.Sub1.setSizePolicy(sizePolicy6)
        self.Sub1.setMinimumSize(QSize(100, 0))
        self.Sub1.setMaximumSize(QSize(300, 100))
        self.s1 = QLabel(self.Sub1)
        self.s1.setObjectName(u"s1")
        self.s1.setGeometry(QRect(10, 0, 131, 51))
        self.s1.setFont(font10)
        self.s1.setAlignment(Qt.AlignCenter)
        self.Subj2 = QLabel(self.widget_7)
        self.Subj2.setObjectName(u"Subj2")
        self.Subj2.setGeometry(QRect(410, 60, 411, 51))
        self.Subj2.setFont(font12)
        self.Subj2.setAlignment(Qt.AlignCenter)
        self.Subj4 = QLabel(self.widget_7)
        self.Subj4.setObjectName(u"Subj4")
        self.Subj4.setGeometry(QRect(410, 190, 411, 51))
        self.Subj4.setFont(font12)
        self.Subj4.setAlignment(Qt.AlignCenter)
        self.Subj3 = QLabel(self.widget_7)
        self.Subj3.setObjectName(u"Subj3")
        self.Subj3.setGeometry(QRect(40, 190, 371, 51))
        self.Subj3.setFont(font12)
        self.Subj3.setAlignment(Qt.AlignCenter)
        self.Sub2 = QWidget(self.widget_7)
        self.Sub2.setObjectName(u"Sub2")
        self.Sub2.setGeometry(QRect(540, 110, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub2.sizePolicy().hasHeightForWidth())
        self.Sub2.setSizePolicy(sizePolicy6)
        self.Sub2.setMinimumSize(QSize(100, 0))
        self.Sub2.setMaximumSize(QSize(300, 100))
        self.s2 = QLabel(self.Sub2)
        self.s2.setObjectName(u"s2")
        self.s2.setGeometry(QRect(0, 0, 141, 51))
        self.s2.setFont(font10)
        self.s2.setAlignment(Qt.AlignCenter)
        self.Sub3 = QWidget(self.widget_7)
        self.Sub3.setObjectName(u"Sub3")
        self.Sub3.setGeometry(QRect(160, 240, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub3.sizePolicy().hasHeightForWidth())
        self.Sub3.setSizePolicy(sizePolicy6)
        self.Sub3.setMinimumSize(QSize(100, 0))
        self.Sub3.setMaximumSize(QSize(300, 100))
        self.s3 = QLabel(self.Sub3)
        self.s3.setObjectName(u"s3")
        self.s3.setGeometry(QRect(0, 0, 141, 51))
        self.s3.setFont(font10)
        self.s3.setAlignment(Qt.AlignCenter)
        self.Sub4 = QWidget(self.widget_7)
        self.Sub4.setObjectName(u"Sub4")
        self.Sub4.setGeometry(QRect(540, 240, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub4.sizePolicy().hasHeightForWidth())
        self.Sub4.setSizePolicy(sizePolicy6)
        self.Sub4.setMinimumSize(QSize(100, 0))
        self.Sub4.setMaximumSize(QSize(300, 100))
        self.s4 = QLabel(self.Sub4)
        self.s4.setObjectName(u"s4")
        self.s4.setGeometry(QRect(0, 0, 141, 51))
        self.s4.setFont(font10)
        self.s4.setAlignment(Qt.AlignCenter)
        self.Subj5 = QLabel(self.widget_7)
        self.Subj5.setObjectName(u"Subj5")
        self.Subj5.setGeometry(QRect(240, 300, 371, 51))
        self.Subj5.setFont(font12)
        self.Subj5.setAlignment(Qt.AlignCenter)
        self.Sub5 = QWidget(self.widget_7)
        self.Sub5.setObjectName(u"Sub5")
        self.Sub5.setGeometry(QRect(360, 350, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub5.sizePolicy().hasHeightForWidth())
        self.Sub5.setSizePolicy(sizePolicy6)
        self.Sub5.setMinimumSize(QSize(100, 0))
        self.Sub5.setMaximumSize(QSize(300, 100))
        self.s5 = QLabel(self.Sub5)
        self.s5.setObjectName(u"s5")
        self.s5.setGeometry(QRect(0, 0, 141, 51))
        self.s5.setFont(font10)
        self.s5.setAlignment(Qt.AlignCenter)
        self.widget_9 = QWidget(self.d_2)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setGeometry(QRect(830, 0, 871, 421))
        self.Tname_4 = QLabel(self.widget_9)
        self.Tname_4.setObjectName(u"Tname_4")
        self.Tname_4.setGeometry(QRect(170, 10, 461, 51))
        self.Tname_4.setFont(font11)
        self.Sub1_2 = QWidget(self.widget_9)
        self.Sub1_2.setObjectName(u"Sub1_2")
        self.Sub1_2.setGeometry(QRect(130, 120, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub1_2.sizePolicy().hasHeightForWidth())
        self.Sub1_2.setSizePolicy(sizePolicy6)
        self.Sub1_2.setMinimumSize(QSize(100, 0))
        self.Sub1_2.setMaximumSize(QSize(300, 100))
        self.s1_2 = QLabel(self.Sub1_2)
        self.s1_2.setObjectName(u"s1_2")
        self.s1_2.setGeometry(QRect(10, 0, 131, 51))
        self.s1_2.setFont(font10)
        self.s1_2.setAlignment(Qt.AlignCenter)
        self.Subj3_2 = QLabel(self.widget_9)
        self.Subj3_2.setObjectName(u"Subj3_2")
        self.Subj3_2.setGeometry(QRect(10, 200, 371, 51))
        self.Subj3_2.setFont(font12)
        self.Subj3_2.setAlignment(Qt.AlignCenter)
        self.Subj5_2 = QLabel(self.widget_9)
        self.Subj5_2.setObjectName(u"Subj5_2")
        self.Subj5_2.setGeometry(QRect(210, 310, 371, 51))
        self.Subj5_2.setFont(font12)
        self.Subj5_2.setAlignment(Qt.AlignCenter)
        self.Sub5_2 = QWidget(self.widget_9)
        self.Sub5_2.setObjectName(u"Sub5_2")
        self.Sub5_2.setGeometry(QRect(330, 360, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub5_2.sizePolicy().hasHeightForWidth())
        self.Sub5_2.setSizePolicy(sizePolicy6)
        self.Sub5_2.setMinimumSize(QSize(100, 0))
        self.Sub5_2.setMaximumSize(QSize(300, 100))
        self.s5_2 = QLabel(self.Sub5_2)
        self.s5_2.setObjectName(u"s5_2")
        self.s5_2.setGeometry(QRect(0, 0, 141, 51))
        self.s5_2.setFont(font10)
        self.s5_2.setAlignment(Qt.AlignCenter)
        self.Subj2_2 = QLabel(self.widget_9)
        self.Subj2_2.setObjectName(u"Subj2_2")
        self.Subj2_2.setGeometry(QRect(380, 70, 411, 51))
        self.Subj2_2.setFont(font12)
        self.Subj2_2.setAlignment(Qt.AlignCenter)
        self.Sub3_2 = QWidget(self.widget_9)
        self.Sub3_2.setObjectName(u"Sub3_2")
        self.Sub3_2.setGeometry(QRect(130, 250, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub3_2.sizePolicy().hasHeightForWidth())
        self.Sub3_2.setSizePolicy(sizePolicy6)
        self.Sub3_2.setMinimumSize(QSize(100, 0))
        self.Sub3_2.setMaximumSize(QSize(300, 100))
        self.s3_2 = QLabel(self.Sub3_2)
        self.s3_2.setObjectName(u"s3_2")
        self.s3_2.setGeometry(QRect(0, 0, 141, 51))
        self.s3_2.setFont(font10)
        self.s3_2.setAlignment(Qt.AlignCenter)
        self.Sub2_5 = QWidget(self.widget_9)
        self.Sub2_5.setObjectName(u"Sub2_5")
        self.Sub2_5.setGeometry(QRect(510, 120, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub2_5.sizePolicy().hasHeightForWidth())
        self.Sub2_5.setSizePolicy(sizePolicy6)
        self.Sub2_5.setMinimumSize(QSize(100, 0))
        self.Sub2_5.setMaximumSize(QSize(300, 100))
        self.s2_2 = QLabel(self.Sub2_5)
        self.s2_2.setObjectName(u"s2_2")
        self.s2_2.setGeometry(QRect(0, 0, 141, 51))
        self.s2_2.setFont(font10)
        self.s2_2.setAlignment(Qt.AlignCenter)
        self.Subj1_5 = QLabel(self.widget_9)
        self.Subj1_5.setObjectName(u"Subj1_5")
        self.Subj1_5.setGeometry(QRect(10, 70, 371, 51))
        self.Subj1_5.setFont(font12)
        self.Subj1_5.setAlignment(Qt.AlignCenter)
        self.Subj4_2 = QLabel(self.widget_9)
        self.Subj4_2.setObjectName(u"Subj4_2")
        self.Subj4_2.setGeometry(QRect(380, 200, 411, 51))
        self.Subj4_2.setFont(font12)
        self.Subj4_2.setAlignment(Qt.AlignCenter)
        self.Sub4_2 = QWidget(self.widget_9)
        self.Sub4_2.setObjectName(u"Sub4_2")
        self.Sub4_2.setGeometry(QRect(510, 250, 141, 51))
        sizePolicy6.setHeightForWidth(self.Sub4_2.sizePolicy().hasHeightForWidth())
        self.Sub4_2.setSizePolicy(sizePolicy6)
        self.Sub4_2.setMinimumSize(QSize(100, 0))
        self.Sub4_2.setMaximumSize(QSize(300, 100))
        self.s4_2 = QLabel(self.Sub4_2)
        self.s4_2.setObjectName(u"s4_2")
        self.s4_2.setGeometry(QRect(0, 0, 141, 51))
        self.s4_2.setFont(font10)
        self.s4_2.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.d_2, 1, 0, 1, 2)
        self.main_pages.addWidget(self.Home)
        self.Updt_Details_Page = QWidget()
        self.Updt_Details_Page.setObjectName(u"Updt_Details_Page")
        sizePolicy.setHeightForWidth(self.Updt_Details_Page.sizePolicy().hasHeightForWidth())
        self.Updt_Details_Page.setSizePolicy(sizePolicy)
        self.b = QWidget(self.Updt_Details_Page)
        self.b.setObjectName(u"b")
        self.b.setGeometry(QRect(370, 470, 803, 413))
        self.label_17 = QLabel(self.b)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(260, 260, 462, 50))
        self.label_17.setMaximumSize(QSize(16777215, 50))
        font13 = QFont()
        font13.setFamily(u"Maiandra GD")
        font13.setPointSize(19)
        self.label_17.setFont(font13)
        self.label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_18 = QLabel(self.b)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(270, 20, 462, 50))
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QSize(16777215, 50))
        font14 = QFont()
        font14.setFamily(u"Maiandra GD")
        font14.setPointSize(27)
        self.label_18.setFont(font14)
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Update_pass = QPushButton(self.b)
        self.Update_pass.setObjectName(u"Update_pass")
        self.Update_pass.setGeometry(QRect(260, 340, 231, 51))
        sizePolicy7 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.Update_pass.sizePolicy().hasHeightForWidth())
        self.Update_pass.setSizePolicy(sizePolicy7)
        self.Update_pass.setMinimumSize(QSize(0, 50))
        self.Update_pass.setMaximumSize(QSize(500, 16777215))
        font15 = QFont()
        font15.setFamily(u"white allies")
        font15.setPointSize(22)
        self.Update_pass.setFont(font15)
        self.Update_pass.setCursor(QCursor(Qt.PointingHandCursor))
        self.pass2 = QLineEdit(self.b)
        self.pass2.setObjectName(u"pass2")
        self.pass2.setGeometry(QRect(260, 110, 462, 50))
        sizePolicy.setHeightForWidth(self.pass2.sizePolicy().hasHeightForWidth())
        self.pass2.setSizePolicy(sizePolicy)
        self.pass2.setMaximumSize(QSize(16777215, 50))
        self.pass2.setFont(font7)
        self.pass2.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.pass2.setEchoMode(QLineEdit.Password)
        self.label_16 = QLabel(self.b)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(32, 180, 225, 50))
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QSize(225, 0))
        self.label_16.setFont(font12)
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.New_pass = QLineEdit(self.b)
        self.New_pass.setObjectName(u"New_pass")
        self.New_pass.setGeometry(QRect(260, 180, 462, 50))
        sizePolicy.setHeightForWidth(self.New_pass.sizePolicy().hasHeightForWidth())
        self.New_pass.setSizePolicy(sizePolicy)
        self.New_pass.setMaximumSize(QSize(16777215, 50))
        self.New_pass.setFont(font7)
        self.label_19 = QLabel(self.b)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(32, 110, 225, 50))
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QSize(225, 0))
        font16 = QFont()
        font16.setFamily(u"Maiandra GD")
        font16.setPointSize(25)
        self.label_19.setFont(font16)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.a = QWidget(self.Updt_Details_Page)
        self.a.setObjectName(u"a")
        self.a.setGeometry(QRect(370, 0, 803, 413))
        self.a.setMaximumSize(QSize(803, 16777215))
        self.Update_ph = QPushButton(self.a)
        self.Update_ph.setObjectName(u"Update_ph")
        self.Update_ph.setGeometry(QRect(250, 340, 300, 51))
        sizePolicy7.setHeightForWidth(self.Update_ph.sizePolicy().hasHeightForWidth())
        self.Update_ph.setSizePolicy(sizePolicy7)
        self.Update_ph.setMinimumSize(QSize(0, 50))
        self.Update_ph.setMaximumSize(QSize(500, 16777215))
        self.Update_ph.setFont(font15)
        self.Update_ph.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_15 = QLabel(self.a)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 260, 462, 50))
        self.label_15.setMaximumSize(QSize(16777215, 50))
        self.label_15.setFont(font13)
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.New_phno = QLineEdit(self.a)
        self.New_phno.setObjectName(u"New_phno")
        self.New_phno.setGeometry(QRect(300, 190, 462, 50))
        sizePolicy.setHeightForWidth(self.New_phno.sizePolicy().hasHeightForWidth())
        self.New_phno.setSizePolicy(sizePolicy)
        self.New_phno.setMaximumSize(QSize(16777215, 50))
        self.New_phno.setFont(font7)
        self.label_12 = QLabel(self.a)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(72, 120, 225, 50))
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QSize(225, 0))
        self.label_12.setFont(font16)
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pass1 = QLineEdit(self.a)
        self.pass1.setObjectName(u"pass1")
        self.pass1.setGeometry(QRect(300, 120, 462, 50))
        sizePolicy.setHeightForWidth(self.pass1.sizePolicy().hasHeightForWidth())
        self.pass1.setSizePolicy(sizePolicy)
        self.pass1.setMaximumSize(QSize(16777215, 50))
        self.pass1.setFont(font7)
        self.pass1.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.pass1.setEchoMode(QLineEdit.Password)
        self.label_14 = QLabel(self.a)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 20, 462, 50))
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QSize(16777215, 50))
        self.label_14.setFont(font14)
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_13 = QLabel(self.a)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(72, 190, 225, 50))
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QSize(225, 0))
        self.label_13.setFont(font12)
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.main_pages.addWidget(self.Updt_Details_Page)
        self.Attd_Verify_Uptd_page = QWidget()
        self.Attd_Verify_Uptd_page.setObjectName(u"Attd_Verify_Uptd_page")
        self.widget_8 = QWidget(self.Attd_Verify_Uptd_page)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(-1, -1, 1961, 861))
        self.widget_10 = QWidget(self.widget_8)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(0, 0, 1951, 80))
        self.Attd_verify = QLabel(self.widget_10)
        self.Attd_verify.setObjectName(u"Attd_verify")
        self.Attd_verify.setGeometry(QRect(60, 20, 1581, 41))
        font17 = QFont()
        font17.setFamily(u"Maiandra GD")
        font17.setPointSize(34)
        self.Attd_verify.setFont(font17)
        self.Attd_verify.setAlignment(Qt.AlignCenter)
        self.widget_11 = QWidget(self.widget_8)
        self.widget_11.setObjectName(u"widget_11")
        self.widget_11.setGeometry(QRect(0, 90, 1921, 651))
        self.widget_12 = QWidget(self.widget_11)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setGeometry(QRect(360, 90, 951, 551))
        self.pic = QLabel(self.widget_12)
        self.pic.setObjectName(u"pic")
        self.pic.setGeometry(QRect(70, 0, 951, 551))
        self.Cls_Visuals = QLabel(self.widget_11)
        self.Cls_Visuals.setObjectName(u"Cls_Visuals")
        self.Cls_Visuals.setGeometry(QRect(670, 30, 221, 31))
        self.Cls_Visuals.setFont(font16)
        self.filename = QLabel(self.widget_11)
        self.filename.setObjectName(u"filename")
        self.filename.setGeometry(QRect(900, 30, 221, 31))
        self.filename.setFont(font16)
        self.widget_13 = QWidget(self.widget_8)
        self.widget_13.setObjectName(u"widget_13")
        self.widget_13.setGeometry(QRect(0, 750, 1921, 175))
        self.widget_13.setMinimumSize(QSize(981, 175))
        font18 = QFont()
        font18.setItalic(False)
        self.widget_13.setFont(font18)
        self.ra = QPushButton(self.widget_13)
        self.ra.setObjectName(u"ra")
        self.ra.setGeometry(QRect(1010, 30, 150, 50))
        self.ra.setMinimumSize(QSize(150, 50))
        font19 = QFont()
        font19.setFamily(u"white allies")
        font19.setPointSize(25)
        font19.setBold(False)
        font19.setWeight(50)
        self.ra.setFont(font19)
        self.pic_cnt = QLabel(self.widget_13)
        self.pic_cnt.setObjectName(u"pic_cnt")
        self.pic_cnt.setGeometry(QRect(890, 50, 321, 20))
        self.pic_cnt.setFont(font13)
        self.la = QPushButton(self.widget_13)
        self.la.setObjectName(u"la")
        self.la.setGeometry(QRect(670, 30, 150, 50))
        self.la.setMinimumSize(QSize(150, 50))
        font20 = QFont()
        font20.setFamily(u"white allies")
        font20.setPointSize(25)
        font20.setBold(False)
        font20.setItalic(False)
        font20.setWeight(50)
        self.la.setFont(font20)
        self.main_pages.addWidget(self.Attd_Verify_Uptd_page)
        self.Academics_page = QWidget()
        self.Academics_page.setObjectName(u"Academics_page")
        self.widget_24 = QWidget(self.Academics_page)
        self.widget_24.setObjectName(u"widget_24")
        self.widget_24.setGeometry(QRect(-10, -10, 1951, 80))
        self.Acdm = QLabel(self.widget_24)
        self.Acdm.setObjectName(u"Acdm")
        self.Acdm.setGeometry(QRect(60, 20, 1581, 41))
        self.Acdm.setFont(font17)
        self.Acdm.setAlignment(Qt.AlignCenter)
        self.widget_25 = QWidget(self.Academics_page)
        self.widget_25.setObjectName(u"widget_25")
        self.widget_25.setGeometry(QRect(-10, 80, 1951, 801))
        self.Acdm_2 = QLabel(self.widget_25)
        self.Acdm_2.setObjectName(u"Acdm_2")
        self.Acdm_2.setGeometry(QRect(560, 10, 201, 41))
        self.Acdm_2.setFont(font17)
        self.Acdm_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.sem = QComboBox(self.widget_25)
        self.sem.setObjectName(u"sem")
        self.sem.setGeometry(QRect(750, 10, 311, 50))
        self.sem.setFont(font7)
        self.sem.setStyleSheet(u"")
        self.Subj1_m = QLabel(self.widget_25)
        self.Subj1_m.setObjectName(u"Subj1_m")
        self.Subj1_m.setGeometry(QRect(140, 150, 621, 51))
        self.Subj1_m.setFont(font17)
        self.Subj1_m.setAlignment(Qt.AlignCenter)
        self.Subj2_m = QLabel(self.widget_25)
        self.Subj2_m.setObjectName(u"Subj2_m")
        self.Subj2_m.setGeometry(QRect(820, 150, 711, 51))
        self.Subj2_m.setFont(font17)
        self.Subj2_m.setAlignment(Qt.AlignCenter)
        self.Sub1m = QWidget(self.widget_25)
        self.Sub1m.setObjectName(u"Sub1m")
        self.Sub1m.setGeometry(QRect(350, 210, 201, 81))
        sizePolicy6.setHeightForWidth(self.Sub1m.sizePolicy().hasHeightForWidth())
        self.Sub1m.setSizePolicy(sizePolicy6)
        self.Sub1m.setMinimumSize(QSize(100, 0))
        self.Sub1m.setMaximumSize(QSize(300, 100))
        self.s1_m = QLabel(self.Sub1m)
        self.s1_m.setObjectName(u"s1_m")
        self.s1_m.setGeometry(QRect(30, 10, 131, 51))
        self.s1_m.setFont(font10)
        self.s1_m.setAlignment(Qt.AlignCenter)
        self.Sub2m = QWidget(self.widget_25)
        self.Sub2m.setObjectName(u"Sub2m")
        self.Sub2m.setGeometry(QRect(1070, 210, 201, 81))
        sizePolicy6.setHeightForWidth(self.Sub2m.sizePolicy().hasHeightForWidth())
        self.Sub2m.setSizePolicy(sizePolicy6)
        self.Sub2m.setMinimumSize(QSize(100, 0))
        self.Sub2m.setMaximumSize(QSize(300, 100))
        self.s2_m = QLabel(self.Sub2m)
        self.s2_m.setObjectName(u"s2_m")
        self.s2_m.setGeometry(QRect(30, 10, 131, 51))
        self.s2_m.setFont(font10)
        self.s2_m.setAlignment(Qt.AlignCenter)
        self.Sub3m = QWidget(self.widget_25)
        self.Sub3m.setObjectName(u"Sub3m")
        self.Sub3m.setGeometry(QRect(350, 390, 201, 81))
        sizePolicy6.setHeightForWidth(self.Sub3m.sizePolicy().hasHeightForWidth())
        self.Sub3m.setSizePolicy(sizePolicy6)
        self.Sub3m.setMinimumSize(QSize(100, 0))
        self.Sub3m.setMaximumSize(QSize(300, 100))
        self.s3_m = QLabel(self.Sub3m)
        self.s3_m.setObjectName(u"s3_m")
        self.s3_m.setGeometry(QRect(30, 10, 131, 51))
        self.s3_m.setFont(font10)
        self.s3_m.setAlignment(Qt.AlignCenter)
        self.Subj4_m = QLabel(self.widget_25)
        self.Subj4_m.setObjectName(u"Subj4_m")
        self.Subj4_m.setGeometry(QRect(820, 330, 711, 51))
        self.Subj4_m.setFont(font17)
        self.Subj4_m.setAlignment(Qt.AlignCenter)
        self.Subj3_m = QLabel(self.widget_25)
        self.Subj3_m.setObjectName(u"Subj3_m")
        self.Subj3_m.setGeometry(QRect(140, 330, 621, 51))
        self.Subj3_m.setFont(font17)
        self.Subj3_m.setAlignment(Qt.AlignCenter)
        self.Sub4m = QWidget(self.widget_25)
        self.Sub4m.setObjectName(u"Sub4m")
        self.Sub4m.setGeometry(QRect(1070, 390, 201, 81))
        sizePolicy6.setHeightForWidth(self.Sub4m.sizePolicy().hasHeightForWidth())
        self.Sub4m.setSizePolicy(sizePolicy6)
        self.Sub4m.setMinimumSize(QSize(100, 0))
        self.Sub4m.setMaximumSize(QSize(300, 100))
        self.s4_m = QLabel(self.Sub4m)
        self.s4_m.setObjectName(u"s4_m")
        self.s4_m.setGeometry(QRect(30, 10, 131, 51))
        self.s4_m.setFont(font10)
        self.s4_m.setAlignment(Qt.AlignCenter)
        self.Subj5_m = QLabel(self.widget_25)
        self.Subj5_m.setObjectName(u"Subj5_m")
        self.Subj5_m.setGeometry(QRect(450, 490, 711, 51))
        self.Subj5_m.setFont(font17)
        self.Subj5_m.setAlignment(Qt.AlignCenter)
        self.Sub5m = QWidget(self.widget_25)
        self.Sub5m.setObjectName(u"Sub5m")
        self.Sub5m.setGeometry(QRect(700, 550, 201, 81))
        sizePolicy6.setHeightForWidth(self.Sub5m.sizePolicy().hasHeightForWidth())
        self.Sub5m.setSizePolicy(sizePolicy6)
        self.Sub5m.setMinimumSize(QSize(100, 0))
        self.Sub5m.setMaximumSize(QSize(300, 100))
        self.s5_m = QLabel(self.Sub5m)
        self.s5_m.setObjectName(u"s5_m")
        self.s5_m.setGeometry(QRect(30, 10, 131, 51))
        self.s5_m.setFont(font10)
        self.s5_m.setAlignment(Qt.AlignCenter)
        self.Tp = QLabel(self.widget_25)
        self.Tp.setObjectName(u"Tp")
        self.Tp.setGeometry(QRect(560, 710, 351, 51))
        self.Tp.setFont(font17)
        self.Tp.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.Tp_ = QWidget(self.widget_25)
        self.Tp_.setObjectName(u"Tp_")
        self.Tp_.setGeometry(QRect(910, 700, 201, 81))
        sizePolicy6.setHeightForWidth(self.Tp_.sizePolicy().hasHeightForWidth())
        self.Tp_.setSizePolicy(sizePolicy6)
        self.Tp_.setMinimumSize(QSize(100, 0))
        self.Tp_.setMaximumSize(QSize(300, 100))
        self.percent = QLabel(self.Tp_)
        self.percent.setObjectName(u"percent")
        self.percent.setGeometry(QRect(30, 10, 131, 51))
        self.percent.setFont(font10)
        self.percent.setAlignment(Qt.AlignCenter)
        self.main_pages.addWidget(self.Academics_page)
        self.Help_page = QWidget()
        self.Help_page.setObjectName(u"Help_page")
        self.widget_17 = QWidget(self.Help_page)
        self.widget_17.setObjectName(u"widget_17")
        self.widget_17.setGeometry(QRect(0, 0, 1931, 871))
        self.widget_19 = QWidget(self.widget_17)
        self.widget_19.setObjectName(u"widget_19")
        self.widget_19.setGeometry(QRect(250, 180, 1111, 471))
        self.widget_19.setStyleSheet(u"QPushButton{\n"
"text-align:left;\n"
"padding:5px 10px;\n"
"border-radius:50px;\n"
"background-color:rgb(255,255, 255);\n"
"color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"text-align:left;\n"
"background-color: rgb(97, 97, 97);\n"
"border-radius:50px;\n"
"color: rgb(255,255,255);\n"
"}")
        self.label_3 = QLabel(self.widget_19)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(460, 10, 311, 61))
        font21 = QFont()
        font21.setFamily(u"Maiandra GD")
        font21.setPointSize(36)
        self.label_3.setFont(font21)
        self.label_29 = QLabel(self.widget_19)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 90, 251, 50))
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QSize(225, 0))
        self.label_29.setFont(font16)
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_30 = QLabel(self.widget_19)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(460, 90, 251, 50))
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QSize(225, 0))
        self.label_30.setFont(font16)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_31 = QLabel(self.widget_19)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(850, 90, 251, 50))
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QSize(225, 0))
        self.label_31.setFont(font16)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.widget_19)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 140, 251, 101))
        font22 = QFont()
        font22.setFamily(u"Maiandra GD")
        font22.setPointSize(15)
        self.pushButton.setFont(font22)
        self.pushButton.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u"call.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QSize(45, 49))
        self.pushButton_2 = QPushButton(self.widget_19)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 260, 251, 101))
        font23 = QFont()
        font23.setFamily(u"Maiandra GD")
        font23.setPointSize(10)
        self.pushButton_2.setFont(font23)
        self.pushButton_2.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u"m.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QSize(42, 48))
        self.pushButton_3 = QPushButton(self.widget_19)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(460, 260, 251, 101))
        self.pushButton_3.setFont(font23)
        self.pushButton_3.setStyleSheet(u"")
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QSize(42, 48))
        self.pushButton_5 = QPushButton(self.widget_19)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(850, 260, 251, 101))
        self.pushButton_5.setFont(font23)
        self.pushButton_5.setStyleSheet(u"")
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QSize(42, 48))
        self.pushButton_4 = QPushButton(self.widget_19)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(460, 140, 251, 101))
        self.pushButton_4.setFont(font22)
        self.pushButton_4.setStyleSheet(u"")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QSize(45, 49))
        self.pushButton_6 = QPushButton(self.widget_19)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(850, 140, 251, 101))
        self.pushButton_6.setFont(font22)
        self.pushButton_6.setStyleSheet(u"")
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QSize(45, 49))
        self.main_pages.addWidget(self.Help_page)
        self.Setting_page = QWidget()
        self.Setting_page.setObjectName(u"Setting_page")
        self.widget_16 = QWidget(self.Setting_page)
        self.widget_16.setObjectName(u"widget_16")
        self.widget_16.setGeometry(QRect(0, 10, 1931, 871))
        self.widget_18 = QWidget(self.widget_16)
        self.widget_18.setObjectName(u"widget_18")
        self.widget_18.setGeometry(QRect(260, 190, 1111, 471))
        self.label = QLabel(self.widget_18)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(520, 10, 311, 61))
        self.label.setFont(font21)
        self.label_21 = QLabel(self.widget_18)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(300, 130, 225, 50))
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QSize(225, 0))
        self.label_21.setFont(font16)
        self.label_21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sub_menu_2 = QComboBox(self.widget_18)
        self.sub_menu_2.setObjectName(u"sub_menu_2")
        self.sub_menu_2.setGeometry(QRect(550, 130, 311, 50))
        self.sub_menu_2.setFont(font7)
        self.sub_menu_2.setStyleSheet(u"")
        self.sub_menu_3 = QComboBox(self.widget_18)
        self.sub_menu_3.setObjectName(u"sub_menu_3")
        self.sub_menu_3.setGeometry(QRect(550, 200, 311, 50))
        self.sub_menu_3.setFont(font7)
        self.sub_menu_3.setStyleSheet(u"")
        self.label_27 = QLabel(self.widget_18)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(300, 200, 225, 50))
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QSize(225, 0))
        self.label_27.setFont(font16)
        self.label_27.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sub_menu_4 = QComboBox(self.widget_18)
        self.sub_menu_4.setObjectName(u"sub_menu_4")
        self.sub_menu_4.setGeometry(QRect(550, 270, 311, 50))
        self.sub_menu_4.setFont(font7)
        self.sub_menu_4.setStyleSheet(u"")
        self.label_28 = QLabel(self.widget_18)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(244, 270, 281, 50))
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QSize(225, 0))
        self.label_28.setFont(font16)
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.main_pages.addWidget(self.Setting_page)
        self.verticalLayout_4.addWidget(self.main_pages)
        self.horizontalLayout.addWidget(self.widget_14)
        self.verticalLayout.addWidget(self.Body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.main_pages.setCurrentIndex(0)
        self.file_list=None
        self.file_counter=None
        dir="E:/MIC/project/Code/New folder/GUI/Cls_Visuals/"
        self.file_list=[dir+f for f in os.listdir(dir)]
        self.file_counter=0        
        f=os.path.splitext(os.path.basename(self.file_list[self.file_counter]))
        self.filename.setText(f[0])
        self.pic_cnt.setText(str(self.file_counter+1)+"/"+str(len(self.file_list)))
        self.current_file=self.file_list[self.file_counter]
        pixmap=PySide2.QtGui.QPixmap(self.current_file)
        pixmap=pixmap.scaled(951, 551)
        self.pic.setPixmap(pixmap)
        sem=['1','2','3','4','5']
        lang=['English','മലയാളം','हिंदी','தமிழ்','español','français','日本','中國人']
        theme=['Light','Dark','System Default']
        bg=['bg_img 1','bg_img 2','bg_img 3','bg_img 4']
        self.sem.addItems(sem)
        self.sem.setCurrentIndex(4)
        self.sem.currentIndexChanged.connect(self.mark)
        self.sub_menu_2.addItems(lang)
        self.sub_menu_3.addItems(theme)
        self.sub_menu_4.addItems(bg)
        self.stud_attd()
        self.st_sub_attd()
        self.stu_date_atted()
        self.mark()
        self.calendar.selectionChanged.connect(self.stu_date_atted)
        self.Update_ph.clicked.connect(self.u_ph)
        self.Update_pass.clicked.connect(self.u_pass)
        self.logout.clicked.connect(MainWindow.close)
        self.logout.clicked.connect(self.out) 
        self.label_15.setHidden(True)       
        self.label_17.setHidden(True)
        self.la.clicked.connect(self.prev_img)       
        self.ra.clicked.connect(self.next_img)      
        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi


    def mark(self):
        sub=subjects()
        self.Subj1_m.setText(sub[0][0])
        self.Subj2_m.setText(sub[1][0])
        self.Subj3_m.setText(sub[2][0])
        self.Subj4_m.setText(sub[3][0])
        self.Subj5_m.setText(sub[4][0])
        s=self.sem.currentText()
        id_=str(self.Tid.text())
        id_=id_[12:]
        res=db_marks(id_,s)
        self.s1_m.setText(str(res[0][0]))
        self.s2_m.setText(str(res[1][0]))
        self.s3_m.setText(str(res[2][0]))
        self.s4_m.setText(str(res[3][0]))
        self.s5_m.setText(str(res[4][0]))
        self.percent.setText(str(res[5][0]))


    def u_pass(self):
        id_=str(self.Tid.text())
        id_=id_[12:]
        password=self.pass2.text()
        new_pass=self.New_pass.text()
        db_pass=logins_db(id_)
        if(password != db_pass[0][0]):
            self.label_17.setText("Incorrect Password")
            self.label_17.setHidden(False)
            self.pass2.clear()
            self.New_pass.clear()
        
        elif(len(new_pass)<5):
            self.label_17.setText("Enter a Password of length 5 or more")
            self.label_17.setHidden(False)
            self.New_pass.clear()

        elif(new_pass==password):
            self.label_17.setText("New Password is same as current password")
            self.label_17.setHidden(False)
            self.New_pass.clear()

        else:
            pass_update(id_,new_pass)
            self.label_17.setText("Password Updated")
            self.label_17.setHidden(False)
            self.pass2.clear()
            self.New_pass.clear()

    def u_ph(self):
        id_=str(self.Tid.text())
        id_=id_[12:]
        password=self.pass1.text()
        new_ph=self.New_phno.text()
        db_pass=logins_db(id_)
        if(password != db_pass[0][0]):
            self.label_15.setText("Incorrect Password")
            self.label_15.setHidden(False)
            self.pass1.clear()
            self.New_phno.clear()
        
        elif(len(new_ph)!=10 or new_ph.isdigit()!=True):
            self.label_15.setText("Enter a valid Phone Number")
            self.label_15.setHidden(False)
            self.New_phno.clear() 
        
        else:
            db_update(id_,new_ph)
            self.label_15.setText("Phone Number Updated")
            self.label_15.setHidden(False)
            self.st_detail()
            self.pass1.clear()
            self.New_phno.clear()

    def st_detail(self):
        id_=str(self.Tid.text())
        id_=id_[12:]
        result=st_db(id_)
        self.TPh.setText("Phone Number: "+str(result[0][2]))
        

    def stu_date_atted(self):
        sub=subjects()
        self.Subj1_5.setText(sub[0][0])
        self.Subj2_2.setText(sub[1][0])
        self.Subj3_2.setText(sub[2][0])
        self.Subj4_2.setText(sub[3][0])
        self.Subj5_2.setText(sub[4][0])
        id_=str(self.Tid.text())
        id_=id_[12:]
        d=self.calendar.selectedDate()
        d=str(d.toPython())
        self.Tname_4.setText("Attendance on "+d)
        res=st_db_date_atted(d,id_)
        if(len(res)<2):
            self.s1_2.setText(str("-"))
            self.s2_2.setText(str("-"))
            self.s3_2.setText(str("-"))
            self.s4_2.setText(str("-"))
            self.s5_2.setText(str("-"))
        else:
            if(str(res[0][0])=='0'):
                self.s1_2.setText("-")
            else:
                self.s1_2.setText(str(res[1][0])+" / "+str(res[0][0]))
            if(str(res[0][1])=='0'):
                self.s2_2.setText("-")
            else:
                self.s2_2.setText(str(res[1][1])+" / "+str(res[0][1]))
            if(str(res[0][2])=='0'):
                self.s3_2.setText("-")
            else:
                self.s3_2.setText(str(res[1][2])+" / "+str(res[0][2]))
            if(str(res[0][3])=='0'):
                self.s4_2.setText("-")
            else:
                self.s4_2.setText(str(res[1][3])+" / "+str(res[0][3]))
            if(str(res[0][4])=='0'):
                self.s5_2.setText("-")
            else:
                self.s5_2.setText(str(res[1][4])+" / "+str(res[0][4]))           
            
    
    def stud_attd(self):
        id_=str(self.Tid.text())
        id_=id_[12:]

        res=stud_db_attd(id_)
        self.Th_.setText(str(res[0][0]))
        self.Ph_.setText(str(res[0][1]))
        self.Ah_.setText(str(res[0][2]))
        self.P_.setText(str(res[0][3])+"%")
        
    def st_sub_attd(self):
        sub=subjects()
        self.Subj1_6.setText(sub[0][0])
        self.Subj2.setText(sub[1][0])
        self.Subj3.setText(sub[2][0])
        self.Subj4.setText(sub[3][0])
        self.Subj5.setText(sub[4][0])
        id_=str(self.Tid.text())
        id_=id_[12:]
        res=st_sub_db_attd(id_)
        self.s1.setText(str(res[1][0])+" / "+str(res[0][0]))
        self.s2.setText(str(res[1][1])+" / "+str(res[0][1]))
        self.s3.setText(str(res[1][2])+" / "+str(res[0][2]))
        self.s4.setText(str(res[1][3])+" / "+str(res[0][3]))
        self.s5.setText(str(res[1][4])+" / "+str(res[0][4]))

        
    def next_img(self):
        if self.file_counter is not None:
            self.file_counter += 1
            self.file_counter%=len(self.file_list)
            self.current_file=self.file_list[self.file_counter]
            f=os.path.splitext(os.path.basename(self.file_list[self.file_counter]))
            self.filename.setText(f[0])
            self.pic_cnt.setText(str(self.file_counter+1)+"/"+str(len(self.file_list)))
            pixmap=PySide2.QtGui.QPixmap(self.current_file)
            pixmap=pixmap.scaled(951, 551)
            self.pic.setPixmap(pixmap)

    
    def prev_img(self):
        if self.file_counter is not None:
            self.file_counter -= 1
            self.file_counter%=len(self.file_list)
            self.current_file=self.file_list[self.file_counter]
            f=os.path.splitext(os.path.basename(self.file_list[self.file_counter]))
            self.filename.setText(f[0])
            self.pic_cnt.setText(str(self.file_counter+1)+"/"+str(len(self.file_list)))
            pixmap=PySide2.QtGui.QPixmap(self.current_file)
            pixmap=pixmap.scaled(951, 551)
            self.pic.setPixmap(pixmap)
    
    def out(self):
        from subprocess import run
        run(['python',"gui.py"])
    
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Face Recognition Attendance System", None))
        self.logout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.home_btn.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.Updt_Details.setText(QCoreApplication.translate("MainWindow", u"Update Student Details", None))
        self.Attd_verify_Uptd.setText(QCoreApplication.translate("MainWindow", u"Attendance Verification ", None))
        self.Academics.setText(QCoreApplication.translate("MainWindow", u"Academics", None))
        self.Help.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.Settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.Tname.setText(QCoreApplication.translate("MainWindow", u"Student Name: ABCDEFGHI", None))
        self.Tid.setText(QCoreApplication.translate("MainWindow", u"Student ID: 7", None))
        self.Cid.setText(QCoreApplication.translate("MainWindow", u"Class ID: lmn", None))
        self.TPh.setText(QCoreApplication.translate("MainWindow", u" Phone Number: 0123456789", None))
        self.Tname_2.setText(QCoreApplication.translate("MainWindow", u"Attendance Details", None))
        self.Th_.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Tname_5.setText(QCoreApplication.translate("MainWindow", u"Total Hours", None))
        self.Tname_6.setText(QCoreApplication.translate("MainWindow", u"Present Hours", None))
        self.Ph_.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Tname_7.setText(QCoreApplication.translate("MainWindow", u"Absent Hours", None))
        self.Ah_.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Tname_8.setText(QCoreApplication.translate("MainWindow", u"Percrntage", None))
        self.P_.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.subattd.setText(QCoreApplication.translate("MainWindow", u"Subject-wise Attendance", None))
        self.Subj1_6.setText(QCoreApplication.translate("MainWindow", u"Subj: 1", None))
        self.s1.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj2.setText(QCoreApplication.translate("MainWindow", u"Subj: 2", None))
        self.Subj4.setText(QCoreApplication.translate("MainWindow", u"Subj: 4", None))
        self.Subj3.setText(QCoreApplication.translate("MainWindow", u"Subj: 3", None))
        self.s2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.s3.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.s4.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj5.setText(QCoreApplication.translate("MainWindow", u"Subj: 5", None))
        self.s5.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Tname_4.setText(QCoreApplication.translate("MainWindow", u"Attendance on 0000/00/00", None))
        self.s1_2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj3_2.setText(QCoreApplication.translate("MainWindow", u"Subj: 3", None))
        self.Subj5_2.setText(QCoreApplication.translate("MainWindow", u"Subj: 5", None))
        self.s5_2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj2_2.setText(QCoreApplication.translate("MainWindow", u"Subj: 2", None))
        self.s3_2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.s2_2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj1_5.setText(QCoreApplication.translate("MainWindow", u"Subj: 1", None))
        self.Subj4_2.setText(QCoreApplication.translate("MainWindow", u"Subj: 4", None))
        self.s4_2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Password Updated", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Update Password", None))
        self.Update_pass.setText(QCoreApplication.translate("MainWindow", u"Update Password", None))
        self.pass2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"New Password", None))
        self.New_pass.setPlaceholderText(QCoreApplication.translate("MainWindow", u"New Password", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.Update_ph.setText(QCoreApplication.translate("MainWindow", u"Update Phone Number", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Phone Number Updated", None))
        self.New_phno.setPlaceholderText(QCoreApplication.translate("MainWindow", u"New Phone Number", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.pass1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Update Phone Number", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"New Phone Number", None))
        self.Attd_verify.setText(QCoreApplication.translate("MainWindow", u"Attendance Verification", None))
        self.pic.setText("")
        self.Cls_Visuals.setText(QCoreApplication.translate("MainWindow", u"Class Visuals :-", None))
        self.filename.setText(QCoreApplication.translate("MainWindow", u"File_name", None))
        self.ra.setText(QCoreApplication.translate("MainWindow", u"Next ->", None))
        self.pic_cnt.setText(QCoreApplication.translate("MainWindow", u"1/3", None))
        self.la.setText(QCoreApplication.translate("MainWindow", u"<- Prev", None))
        self.Acdm.setText(QCoreApplication.translate("MainWindow", u"Academics", None))
        self.Acdm_2.setText(QCoreApplication.translate("MainWindow", u"Semester:", None))
        self.Subj1_m.setText(QCoreApplication.translate("MainWindow", u"Subj: 1", None))
        self.Subj2_m.setText(QCoreApplication.translate("MainWindow", u"Subj: 2", None))
        self.s1_m.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.s2_m.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.s3_m.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj4_m.setText(QCoreApplication.translate("MainWindow", u"Subj: 4", None))
        self.Subj3_m.setText(QCoreApplication.translate("MainWindow", u"Subj: 3", None))
        self.s4_m.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Subj5_m.setText(QCoreApplication.translate("MainWindow", u"Subj: 5", None))
        self.s5_m.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Tp.setText(QCoreApplication.translate("MainWindow", u"Total Percentage:", None))
        self.percent.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Contact Us", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Alby Saji Luka", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Harisankar S.G.", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Vyshnav M.", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"+91 7736094476", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"albyluka02@gmail.com", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"harisankar4785@gmail.com", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"vyshnavmohan20@gmail.com", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"+91 6238574428", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"+91 7907745936", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Language:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Theme:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Background Image:", None))
    # retranslateUi


